# Problem type
problem_type                : 'classification'

# Model
model_type                  : 'VGG16Torch'

# Load/store options
resume_experiment           : False
pretrained_model            : 'custom'
input_model_path            : /home/grupo06/.oscar/work/experiments/vgg16torch_tt100k_28923/VGG16Torch.pth
load_weight_only            : True

### Save options
save_weight_only            : True
model_name                  : 'VGG16Torch'
output_model_path           : null
basic_models_path           : null

# Loss type
loss_type                   : 'cross_entropy_classification'
normalize_loss              : True

# General parameters
train_samples               : -1
valid_samples               : -1
test_samples                : -1
train_batch_size            : 40
valid_batch_size            : 40
test_batch_size             : 40
train                       : True
validation                  : True
test                        : True
predict_test                : True
predict_path_output         : null

# Image properties
size_image_test             : null
resize_image_train          : !!python/tuple [224, 224]
resize_image_valid          : !!python/tuple [224, 224]
resize_image_test           : !!python/tuple [224, 224]
crop_train                  : null
grayscale                   : False

# Dataset properties
train_dataset_path          : '/home/mcv/datasets/M5/classification/BelgiumTSC/train'
valid_dataset_path          : '/home/mcv/datasets/M5/classification/BelgiumTSC/valid'
test_dataset_path           : '/home/mcv/datasets/M5/classification/BelgiumTSC/test'
train_images_txt            : null
train_gt_txt                : null
valid_images_txt            : null
valid_gt_txt                : null
test_images_txt             : null
test_gt_txt                 : null

labels                      : null
map_labels                  : null

num_classes                 : 62
shuffle                     : True
void_class                  : 255

# Training
epochs                      : 100
initial_epoch               : 1
valid_samples_epoch         : -1
is_training                 : True

# Optimizer
optimizer                   : 'SGD'
momentum1                   : 0.9
momentum2                   : 0.9
learning_rate               : 0.001
learning_rate_bias          : 0.001
weight_decay                : 0

# Scheduler
scheduler                   : 'ReduceLROnPlateau'
decay                       : 0.1
sched_patience              : 2

# Save criteria
save_condition              : 'f1_score'

# Early Stopping
early_stopping              : True
stop_condition              : 'f1_score'
patience                    : 5

# Image preprocess
rescale                     : 1.
mean                        : !!python/tuple [127.5, 127.5, 127.5] #[104.00698793, 116.66876762, 122.67891434] #[103.939, 116.779, 123.68] #[0.28689553, 0.32513301, 0.28389176] #[0.37296272, 0.37296272, 0.37296272]
std                         : !!python/tuple [1., 1., 1.] #[0.18696375, 0.19017339, 0.18720214]#[0.21090189, 0.21090189, 0.21090189]

# Data augmentation
hflips                      : False
random_dist                 : False

color_map                   : null
num_images                  : null